from collections import OrderedDict
import os
import gzip
import cupy as cp
import numpy as np
import torch
import torch.backends.cudnn as cudnn
import math
import warnings


def adjust_opt(optAlg, optimizer, epoch):
    if optAlg == 'sgd':
        if epoch < 150:
            lr = 1e-1
        elif epoch == 150:
            lr = 1e-2
        elif epoch == 225:
            lr = 1e-3
        else:
            return

        for param_group in optimizer.param_groups:
            param_group['lr'] = lr


def reproducibility(args, seed):
    torch.manual_seed(seed)
    if args.cuda:
        torch.cuda.manual_seed(seed)
    np.random.seed(seed)
    cudnn.deterministic = True
    # FOR FASTER GPU TRAINING WHEN INPUT SIZE DOESN'T VARY
    # LET'S TEST IT
    cudnn.benchmark = True


def save_volume(volume: cp.ndarray | np.ndarray, path):
    packed_data = np.packbits(volume.flatten())
    packed_data = packed_data.view(np.uint32)
    packed_data = packed_data.byteswap()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with gzip.open(path, "wb") as f:
        f.write(packed_data.tobytes())


@torch.no_grad()
def parse_old_state_dict(state_dict: OrderedDict[str, torch.Tensor]):
    """
    Parse the state dictionary from old format to new format.
    """
    parsed_dict = OrderedDict()

    for key, value in state_dict.items():
        key_split = key.split('.')
        try:
            ops_idx = key_split.index('ops')
        except ValueError:
            ops_idx = -1
        if ops_idx != -1:
            layer_name = key_split[ops_idx + 2]
            if layer_name == 'conv':
                new_key = '.'.join(
                    key_split[:ops_idx + 2] + ['conv1'] + key_split[ops_idx + 3:])
            elif layer_name == 'bn':
                new_key = '.'.join(
                    key_split[:ops_idx + 2] + ['bn1'] + key_split[ops_idx + 3:])
            elif layer_name == 'act':
                new_key = '.'.join(
                    key_split[:ops_idx + 2] + ['relu1'] + key_split[ops_idx + 3:])
            else:
                new_key = key
        else:
            new_key = key

        parsed_dict[new_key] = value

    return parsed_dict


@torch.no_grad()
def parse_dense_state_dict(state_dict, reference_dict):
    """
    Parse the state dictionary from dense to sparse format.
    """

    parsed_dict = OrderedDict()

    for key, value in reference_dict.items():
        if key == 'shapecriptor.coords':
            # Skip this key
            continue
        print(f"Key: {key}")
        if key in state_dict:
            # If the key exists in the state_dict, use its value
            new_value = state_dict[key]
        else:
            key_split = key.split('.')
            if key_split[-1] == 'kernel':
                new_key = '.'.join(key_split[:-1]) + '.weight'
            elif key_split[-2] == 'bn' or key_split[-2] == 'module':
                new_key = '.'.join([*key_split[:-2], key_split[-1]])
            print(f"New key: {new_key}")
            new_value = state_dict[new_key]
        if isinstance(new_value, torch.Tensor):
            # If the value is a tensor, reshape it to match the reference
            if new_value.shape != value.shape:
                if key == 'out_tr.conv2.kernel':
                    new_value = new_value.squeeze(0).squeeze(0).squeeze(0)
                elif key.endswith('kernel'):
                    isUpsample = 'up' in key
                    # Reshape from (out, in, size, size, size) to (size**3, in, out)
                    new_value = new_value.view(new_value.shape[0], new_value.shape[1], -1).permute(
                        *((2, 0, 1) if isUpsample else (2, 1, 0))).contiguous()
                elif key.endswith('bias'):
                    # Reshape from (out) to (1, out)
                    new_value = new_value.unsqueeze(0)
        parsed_dict[key] = new_value

    return parsed_dict


# From https://github.com/huggingface/pytorch-image-models/blob/e44f14d7d2f557b9f3add82ee4f1ed2beefbb30d/timm/layers/weight_init.py#L8
# Because the lib timm doesn't support pytorch nightly
def _trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    # Values are generated by using a truncated uniform distribution and
    # then using the inverse CDF for the normal distribution.
    # Get upper and lower cdf values
    l = norm_cdf((a - mean) / std)
    u = norm_cdf((b - mean) / std)

    # Uniformly fill tensor with values from [l, u], then translate to
    # [2l-1, 2u-1].
    tensor.uniform_(2 * l - 1, 2 * u - 1)

    # Use inverse cdf transform for normal distribution to get truncated
    # standard normal
    tensor.erfinv_()

    # Transform to proper mean, std
    tensor.mul_(std * math.sqrt(2.))
    tensor.add_(mean)

    # Clamp to ensure it's in the proper range
    tensor.clamp_(min=a, max=b)
    return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.

    NOTE: this impl is similar to the PyTorch trunc_normal_, the bounds [a, b] are
    applied while sampling the normal with mean/std applied, therefore a, b args
    should be adjusted to match the range of mean, std args.

    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    with torch.no_grad():
        return _trunc_normal_(tensor, mean, std, a, b)


def restore_checkpoint(model: torch.nn.Module, ckpt_file: str,
                       optimizer: torch.optim.lr_scheduler.LRScheduler = None,
                       scheduler: torch.optim.lr_scheduler.LRScheduler = None,
                       ref_ckpt_file=None):
    r"""
    Restores checkpoint from a pth file and restores optimizer state.

    Args:
        ckpt_file (str): A PyTorch pth file containing model weights.
        optimizer (Optimizer): A vanilla optimizer to have its state restored from.

    Returns:
        int: Global step variable where the model was last checkpointed.
    """
    if not ckpt_file:
        raise ValueError("No checkpoint file to be restored.")

    try:
        ckpt_dict = torch.load(ckpt_file, weights_only=True)
    except RuntimeError:
        ckpt_dict = torch.load(
            ckpt_file, map_location=lambda storage, loc: storage)

    if ref_ckpt_file:
        ref_ckpt_dict = torch.load(ref_ckpt_file, weights_only=True)
        if 'model_state_dict' in ref_ckpt_dict:
            parsed_ckpt_dict = parse_dense_state_dict(
                ckpt_dict['model_state_dict'], ref_ckpt_dict['model_state_dict'])
            ckpt_dict['model_state_dict'] = parsed_ckpt_dict

    # ckpt_dict['model_state_dict'] = parse_old_state_dict(
    #     ckpt_dict['model_state_dict'])

    # Restore model weights
    model.load_state_dict(ckpt_dict['model_state_dict'])

    # Restore optimizer status if existing. Evaluation doesn't need this
    # TODO return optimizer?????
    # If using ref_ckpt_file, don't load optimizer state because it is not a resume
    if optimizer and not ref_ckpt_file:
        optimizer.load_state_dict(ckpt_dict['optimizer_state_dict'])
        optimizer.last_epoch = ckpt_dict['epoch']

    if scheduler and not ref_ckpt_file:
        scheduler.load_state_dict(ckpt_dict['scheduler_state_dict'])

    # Return global step
    return ckpt_dict['epoch'] if not ref_ckpt_file else 0


def save_checkpoint(model: torch.nn.Module,
                    directory: str,
                    epoch: int, loss: float,
                    optimizer=None,
                    scheduler=None,
                    name=None):
    r"""
    Saves checkpoint at a certain global step during training. Optimizer state
    is also saved together.

    Args:
        directory (str): Path to save checkpoint to.
        epoch (int): The training. epoch
        optimizer (Optimizer): Optimizer state to be saved concurrently.
        name (str): The name to save the checkpoint file as.

    Returns:
        None
    """
    # Create directory to save to
    if not os.path.exists(directory):
        os.makedirs(directory)

    # Build checkpoint dict to save.
    ckpt_dict = {
        'model_state_dict':
            model.state_dict(),
        'optimizer_state_dict':
            optimizer.state_dict() if optimizer is not None else None,
        'scheduler_state_dict':
            scheduler.state_dict() if scheduler is not None else None,
        'epoch':
            epoch
    }

    # Save the file with specific name
    if name is None:
        name = "{}_{}_epoch.pth".format(
            os.path.basename(directory),  # netD or netG
            'last')

    torch.save(ckpt_dict, os.path.join(directory, name))
    if not hasattr(model, 'best_loss') or model.best_loss > loss:
        model.best_loss = loss
        name = "{}_BEST.pth".format(
            os.path.basename(directory))
        torch.save(ckpt_dict, os.path.join(directory, name))


def count_params(model):
    r"""
    Computes the number of parameters in this model.

    Args: None

    Returns:
        int: Total number of weight parameters for this model.
        int: Total number of trainable parameters for this model.

    """
    num_total_params = sum(p.numel() for p in model.parameters())
    num_trainable_params = sum(p.numel() for p in model.parameters()
                               if p.requires_grad)

    return num_total_params, num_trainable_params

def time_cuda(fn, *args, key, timings, enabled=True):
    if not enabled:
        return fn(*args)
    start = torch.cuda.Event(enable_timing=True)
    end   = torch.cuda.Event(enable_timing=True)
    torch.cuda.synchronize()
    start.record()
    out = fn(*args)
    end.record()
    torch.cuda.synchronize()
    timings[key] = start.elapsed_time(end)  # milliseconds
    return out


def extract_data(data: dict[str, str | torch.Tensor], key: str) -> torch.Tensor:
    """
    Get the extra data from the input dictionary.
    """
    if key in data:
        return data[key]
    elif key in data["extras"]:
        if isinstance(data["extras"][key], str):
            return data[data["extras"][key]]
        else:
            return data["extras"][key]
    else:
        return None

def prepare_data(data: dict[str, str | torch.Tensor], is_extra: bool = False):
    """
    Prepare the data for the model.
    """
    for key in data:
        if isinstance(data[key], torch.Tensor):
            data[key] = data[key].cuda()
        elif isinstance(data[key], dict):
            data[key] = prepare_data(data[key], is_extra=key == "extras")
        # un-collate the data
        elif is_extra and isinstance(data[key], list) and isinstance(data[key][0], str):
            data[key] = data[key][0]
    return data
